import type { LegalAuditReport } from "@/lib/schemas/legal-audit";

// Turns the disclaimer ("consult a lawyer") into a usable artifact: a
// briefing sheet the user can hand to an attorney. Built client-side from
// data already returned by /api/analyze — no extra Gemini call needed.
export function buildLawyerBriefingMarkdown(report: LegalAuditReport, fileName: string): string {
  const lines: string[] = [
    `# Attorney Briefing Sheet — ${fileName}`,
    "",
    "_Generated by ClauseLens. This is AI-generated informational content, not legal advice — for use in preparing a consultation with a licensed attorney._",
    "",
    `**Contract type:** ${report.contractType}`,
  ];
  if (report.governingLaw) lines.push(`**Governing law:** ${report.governingLaw}`);
  lines.push(
    `**Overall risk score:** ${report.overallRiskScore} / 100`,
    "",
    "## Summary",
    report.executiveSummary,
    "",
    "## High-Priority Clauses to Discuss"
  );

  const priorityClauses = report.flaggedClauses.filter(
    (c) => c.riskLevel === "CRITICAL" || c.riskLevel === "HIGH"
  );
  const clausesToList = priorityClauses.length > 0 ? priorityClauses : report.flaggedClauses;

  for (const clause of clausesToList) {
    lines.push(
      `### ${clause.clauseTitle} (Section ${clause.sectionNumber}) — ${clause.riskLevel}`,
      `> "${clause.exactQuote}"`,
      "",
      `${clause.potentialGotcha}`,
      "",
      `**Suggested question/negotiation point:** ${clause.suggestedNegotiationPoint}`,
      ""
    );
  }

  lines.push(
    "## Questions to Ask Your Attorney",
    ...report.questionsForLawyer.map((q) => `- ${q}`),
    "",
    "## Action Checklist",
    ...report.actionChecklist.map(
      (item) => `- [ ] **${item.urgency}** — ${item.task} (${item.deadlineOrCondition})`
    )
  );

  return lines.join("\n");
}

export function downloadTextFile(content: string, filename: string, mimeType = "text/markdown") {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
